offers/urls.py
from django.urls import path
from .views import OfferListView,OfferDetailView,OfferUpdateView,OfferDeleteView
from .views import OfferCreateView
from offers import views as offers_views
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', OfferListView.as_view(),name='offers-page'),
    path('offer/new/',OfferCreateView.as_view(),name='offer-create'),
    path('offer/<int:pk>/', OfferDetailView.as_view(),name='offer-detail'),
    path('offer/<int:pk>/update/', OfferUpdateView.as_view(),name='offer-update'),
    path('offer/<int:pk>/delete/', OfferDeleteView.as_view(),name='offer-delete'),
    path('product/new/', offers_views.createProduct,name='product-create'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

offerscraping/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from offers import views as offers_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('offers.urls')),
    path('new-entities/', offers_views.newEntities,name="new-entities"),
    path('register/', user_views.register,name="register-page"),
    path('profile/', user_views.profile,name="profile"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'),name="logout"),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
   
]

offers/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
from PIL import Image

class Product(models.Model):
    id_product = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return u"%s" % self.product_name

class Company(models.Model):
    company_name = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    num_workers = models.IntegerField()

    def __str__(self):
        return self.company_name
    
class Maker(models.Model):
    company_name = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    year_build = models.IntegerField()

class Offer(models.Model):
    offer_id = models.AutoField(primary_key=True)
    product_name = models.ForeignKey(Product,on_delete=models.CASCADE)
    company_name = models.CharField(max_length=100)
    sku = models.CharField(max_length=10, default='')
    new_price = models.IntegerField()
    old_price = models.IntegerField()
    discount = models.IntegerField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User,default=1,on_delete=models.CASCADE)
    url_offer = models.URLField(max_length=250,default="",help_text="*In case the offer is local put the shop website URL")
    address = models.CharField(max_length=1000,blank=True,help_text="*Add address in case the offer is in a local site")
    image = models.ImageField(default='default.jpg',upload_to='offers')


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        img.save(self.image.path)

    def __str__(self):
        return u"%s" % self.product_name

    def get_absolute_url(self):
        return reverse('offer-detail',kwargs={'pk':self.pk})

offers/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Product,Offer



class CreateProduct(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['id_product','product_name','category','description']



class CreateOffer(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ['offer_id','product_name','sku','company_name','address','url_offer','new_price','old_price','discount','image']

offers/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import CreateProduct,CreateOffer
from django.contrib import messages
from .models import Offer
from .models import Product
from .models import Company
from .models import Maker




def offers(request):
    #ofertas = Offer.objects.order_by('-offer_id')

    context = {"all_offers":Offer.objects.all()}
    return render(request,'offers/main.html',context)


def newEntities(request):

    return render(request,'offers/entities.html')


def createProduct(request):
    if request.method == 'POST':
        form = CreateProduct(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'The product has been created succesfully, now you can add an offer for this product!!')
            return redirect('offer-create')         
    else:
        form = CreateProduct()

    return render(request,'offers/product_form.html',{'form':form})



class ProductUpdateView(LoginRequiredMixin,UserPassesTestMixin, UpdateView):
    model = Product
    fields = ['id_product','product_name','category','description']


#####################################

class OfferListView(ListView):
    model = Offer
    template_name = 'offers/main.html'
    context_object_name = 'all_offers'
    ordering = ['-offer_id']



class OfferCreateView(LoginRequiredMixin, CreateView):
    model = Offer
    template_name = 'offers/offer_form.html'
    form_class = CreateOffer


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(OfferCreateView,self).form_valid(form)


class OfferDetailView(DetailView):
    model = Offer


class OfferUpdateView(LoginRequiredMixin,UserPassesTestMixin, UpdateView):
    model = Offer
    fields = ['offer_id','product_name','company_name','url_offer','new_price','old_price','discount','image']

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        offer = self.get_object()
        if self.request.user == offer.author:
            return True
        return False

class OfferDeleteView(LoginRequiredMixin,UserPassesTestMixin, DeleteView):
    model = Offer
    success_url = '/'

    def test_func(self):
        offer = self.get_object()
        if self.request.user == offer.author:
            return True
        return False

offers/templates/offers/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'offers/main.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.slim.min.js" crossorigin="anonymous"
    integrity="sha512-6ORWJX/LrnSjBzwefdNUyLCMTIsGoNP6NftMy2UAm1JBm6PRZCO1d7OHBStWpVFZLO+RerTvqX/Z9mBFfCJZ4A=="></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>

    <style>
        header{
            margin-top: 90px;
        }
    </style>

    {% if title %}
        <title>Offers - {{ title }}</title>
    {% else %}
        <title>Offers</title>
    {% endif %}
    <style>

    </style>
 

</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top" style="background: #3C3C3C">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'offers-page' %}">Offers Academy</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <!-- navigation bar left -->
                <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'new-entities' %}">New entities</a>
              </div>
              <!-- navigation bar right -->
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register-page' %}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor%}
        {% endif %}
        {% block content %}{% endblock %}
    </div>>
    {% if user.is_authenticated %}
    <div class="bottom-part">
        <!-- Footer -->
        <footer class="text-center text-white" style="background-color: #3C3C3C;">
          <!-- Grid container -->
            <div class="container p-4 pb-0 footer2">
            <!-- Section: CTA -->
                <section class="mr-2">
                    <p class="d-flex justify-content-center align-items-center mr-2">
                        <span class="me-3 mr-2">Add offer!</span>
                        <a class="btn btn-secondary mt-1 mb-1 mr-2" href="{% url 'offer-create' %}">New Offer!</a>
                    </p>
                </section>
            <!-- Section: CTA -->
            </div>
                <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                © 2021:
                <a class="text-white" href="https://mdbootstrap.com/">Offers Academy</a>
            </div>
        </footer>
    </div>
    {% else %}
    <div class="bottom-part">
        <!-- Footer -->
        <footer class="text-center text-white" style="background-color: #3C3C3C;">
          <!-- Grid container -->
            <div class="container p-4 pb-0 footer2">
            <!-- Section: CTA -->
                <section class="mr-2">
                    <p class="d-flex justify-content-center align-items-center mr-2">
                        <span class="me-3 mr-2">Register here!</span>
                        <a class="btn btn-secondary mt-1 mb-1 mr-2" href="{% url 'register-page' %}">Register</a>
                    </p>
                </section>
            <!-- Section: CTA -->
            </div>
                <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                © 2021:
                <a class="text-white" href="https://mdbootstrap.com/">Offers Academy</a>
            </div>
        </footer>
    </div>
    {% endif %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js" crossorigin="anonymous"
    integrity="sha512-XKa9Hemdy1Ui3KSGgJdgMyYlUg1gM+QhL6cnlyTe2qzMCYm4nAZ1PsVerQzTTXzonUR+dmswHqgJPuwCq1MaAg=="></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" crossorigin="anonymous"
        integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g=="></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css"
    crossorigin="anonymous" integrity="sha512-P5MgMn1jBN01asBgU0z60Qk4QxiXo86+wlFahKrsQf37c9cro517WzVSPPV1tDKzhku2iJ2FVgL67wG03SGnNA=="/>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" />
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    


</body>
</html>

offers/templates/offers/entities.html
{% extends "offers/base.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <h1 class="article-title">Users are able to add offers into the page</h1>
    {% else %}
        <h1 class="article-title">Users are able to add offers into the page</h1>
        <p style="color: red;">*Only users with an account can make an Offer, Sign In or Register below</p>
        
    {% endif %}
    </br>
    <a href="{% url 'offer-create' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Offer</a>
{% endblock content %}

offers/templates/offers/main.html
{% extends "offers/base.html" %}
{% block content %}
    {% for post in all_offers %}
        <article class="media content-section">
          <img class="rounded-circle article-img mr-2" src="{{ post.image.url }}" width="150" height="150">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'offer-detail' post.offer_id %}">{{ post.product_name }}</a></h2>
            <p class="article-content">New price: {{ post.new_price }}€</p>
            <p class="article-content">Old price: <del>{{ post.old_price }}€</del></p>
          </div>
          <a class="btn btn-warning" href={{post.url_offer}} role="button">URL offer</a>
        </article>
    {% endfor %}
{% endblock content %}

offers/templates/offers/offer_confirm_delete.html
{% extends "offers/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class="border-bottom mb-4">Delete Offer</legend>
                <h2>Are you sure you want to delete the post "{{ object.product_name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes,Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'offer-detail' object.offer_id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

offers/templates/offers/offer_detail.html
{% extends "offers/base.html" %}
{% block content %}
    <div vocab="http://schema.org/" typeof="Product">
        <article class="media content-section">
            <div class="mr-2">
                <p><img property="image" class="rounded-circle article-img" src="{{ object.image.url }}" width="250" height="200"></p>
            </div>
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2">Author - {{ object.author }}</a>
                    <small class="text-muted">{{ object.date_posted|date:'F d, Y' }}</small>
                </div>
                <h2 class="article-title"><span property="name"> {{ object.product_name }}</span> - <span property="brand">{{ object.company_name }}</span></h2>
                <p class="article-content" property="sku">SKU: {{ object.sku}}</p>
                <p class="article-content" property="description">Description: {{ object.product_name.description}}</p>
                <div rel = "offers">
                <div typeof = "Offer">
                <p class="article-content">Discount: {{ object.discount }}%</p>
                <p class="article-content">Actual price: <span property="price">{{object.new_price}}</span><span property ="priceCurrency">€</span></p>
                <p class="article-content">Old price: <span property="price"><del>{{ object.old_price }}</del></span> <span property ="priceCurrency">€</span></p>
                {% if object.address %}
                    <p class="article-content" style="color: red">*It's not an online offer, you can check the address below!</p>
                    <a class="btn btn-warning"style="background-color:#ABEBC6" role="button">{{object.address}} </a>
                    <a class="btn btn-warning"style="background-color:#ABEBC6" role="button"><link property="availability" href="https://schema.org/InStock" />Disponibility: In stock</a>
                    <a class="btn btn-warning" property="url" href={{object.url_offer}} role="button">Shop Website</a>
                    <a class="btn btn-warning"style="background-color:grey" role="button">Valid until:<span property="priceValidUntil"> 2021-05-31</span></a>
                {% else %}
                    <a class="btn btn-warning"style="background-color:#ABEBC6" role="button"><link property="availability" href="https://schema.org/InStock" />Disponibility: In stock</a>
                    <a class="btn btn-warning" property="url" href={{object.url_offer}} role="button">URL offer</a>
                    <a class="btn btn-warning"style="background-color:grey" role="button">Valid until:<span property="priceValidUntil"> 2021-05-31</span></a>
                {% endif %}
                </div>
            </div>
            </div>
            {% if object.author == user %}
                    <a class="btn btn-secondary mt-1 mb-1 mr-2" property="url" href="{% url 'offer-update' object.offer_id %}">Update</a>
                    <a class="btn btn-danger mt-1 mb-1 mr-2" property="url" href="{% url 'offer-delete' object.offer_id %}">Delete</a>
            {% endif %}
        </article>
        <div class="form-group">
            <a class="btn btn-primary" href="{% url 'offers-page' %}" role="button" itemprop="url">Go to main page</a>
        </div>
    </div>
{% endblock content %}

offers/templates/offers/offer_form.html
{% extends "offers/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class="border-bottom mb-4">New Offer</legend>
                <div class="new-product"></div>
                    <p>In order to create an Offer you need to select one of the existent products. 
                        If the product that you want to enter doesn't appear in the list, create a new Product here.</p>
                    <a class="btn btn-primary" href="{% url 'product-create' %}" role="button">Create New Product</a>
                </div>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit Offer</button>
            </div>
        </form>
    </div>



    <script>
        $(function() {
            $.getJSON("{% static '/offers/companies.json' %}", {}, function (companies) {
                $("#id_company_name").autocomplete({
                    source: companies
                });
            });
    
            $("#id_address").autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "https://secure.geonames.org/search",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            type: "json",
                            maxRows: 10,
                            name_startsWith: request.term,
                            username: "rogargon"                            // using this user because after register continue saying user not registered xD sorry
                        },
                        success: function( data ) {
                            console.log(data)
                            response( $.map( data.geonames, function( item ) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                    value: item.name,
                                    stateOrProvince: item.adminName1,
                                    countryName: item.countryName
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function( event, ui ) {
                    var name = ui.item.label + ui.item.value + ui.item.stateOrProvince + ui.item.countryName;
                    if (ui.item) {
                        $("#id_address").val(ui.item);                                                     
                    }
                }
            });
        });

    </script>


{% endblock content %}

offers/templates/offers/product_form.html
{% extends "offers/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
 
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class="border-bottom mb-4">New Product</legend>
                {{ form|crispy }}
                <img src="{{ post.image.url }}"/>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit" href="">Submit and go back to offer</button>
            </div>
        </form>
    </div>


    <script>
        $.getJSON("/static/offers/categories.json", {}, function (categories) {
            $("#id_category").autocomplete({
                source: categories
            });
        });
    </script>

{% endblock content %}